/* Auto generated by Twist. Please do not delete this file */

import net.sf.sahi.client.Browser;

import org.springframework.beans.factory.annotation.Autowired;

import com.thoughtworks.twist.core.execution.TwistScenarioDataStore;

import com.thoughtworks.twist.core.BeforeEachStep;

import com.thoughtworks.twist.core.AfterEachStep;

public class ScenarioExecutionHooks {

	private Browser browser;

	@Autowired
	private TwistScenarioDataStore scenarioStore;

	public ScenarioExecutionHooks(Browser browser) {
		this.browser = browser;
	}

	@BeforeEachStep
	public void beforeEachStep() throws Exception {
	
	}

	@AfterEachStep
	public void afterEachStep() throws Exception {
	
	}

}